### PR TITLE
Bug Fix for #216 + Enhancement

### LINKED ISSUE #216: Refresh button in communities refreshes the home feed while still in the community
**How to Reproduce**  
1. Go to a community
2. Tap the new refresh button next to the sorting option
3. Header of the community remains but posts are from other communities

**Expected Behavior**  
Refresh the community posts while respecting sorting option

**Screenshots**  
Screenshot_2023-07-04-13-55-40-942_com hjiangsu thunder

### PR DESCRIPTION
**Pull request by bactaholic**
Howdy,

-Fixed #216, community is now retained after refresh.
-Added refresh button to profile, i refrained from adding pull to refresh as I know @hjiangsu is working on new profile page and I wanted to limit conflicting code, can add though.
-Pull to refresh added to Inbox
-Readjusted alignment of certain text/icons to restore their original positions, as pull-to-refresh modified center

please ignore the excess commits, they are from tests I was running and mistake I accidentally pushed to my fixes-n-features branch

### CODE REVIEW

**Comment by hjiangsu** [comment]
I'm gonna change this to target the develop branch instead of main since theres a lot of changes that happened on develop over the past couple days!

**Comment by bactaholic** [comment]
> I'm gonna change this to target the develop branch instead of main since theres a lot of changes that happened on develop over the past couple days!

Sounds good to me!

File: lib/account/pages/account_page.dart [hunk 1]
```diff
@@ -22,28 +23,92 @@ class _AccountPageState extends State<AccountPage> {
     AuthState authState = context.read<AuthBloc>().state;
     AccountState accountState = context.read<AccountBloc>().state;
 
-    return BlocConsumer<AuthBloc, AuthState>(
-      listener: (context, state) {},
-      builder: (context, state) {
-        if (authState.isLoggedIn && accountState.status == AccountStatus.success) return UserPage(userId: accountState.personView!.person.id, isAccountUser: true);
```
Comment (hjiangsu) [inline lib/account/pages/account_page.dart:28]: There might be conflicting files here - I recently changed the account page to redirect to the UserPage since they share the same base. I think you might have pulled the `develop` branch when it was still in that phase of being transitioned!

**Review by hjiangsu — COMMENTED** [review]
It looks good, the only thing is the comment I made about conflicting files in account_page. I would say the best thing to do here is to remove the changes from the account_page that you've made, but keep everything else in!

**Comment by bactaholic** [comment]
@hjiangsu I removed the refresh from the account page entirely for now, I re-based under develop and made new commits to add back...

-Fixing #216 
-Pull to refresh in inbox
-Text alignment

Account page has been updated to reflect changes from develop branch.

Good to go.
